# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 9, 40, 38, 750156)),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 9, 40, 38, 750122)),
        ),
    ]
