# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160309_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(verbose_name='%m/%d/%Y'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(verbose_name='%m/%d/%Y'),
        ),
    ]
