# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160310_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(help_text='format: YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(help_text='format: YYYY-MM-DD'),
        ),
    ]
